name: create-wordpress-project
type: repository
inputs:
  - name: projectName
    type: string
    description: "Project Name"
repository:
  github: alleyinteractive/create-wordpress-project
  destination: "{{ dasherize inputs.projectName }}"
  postCloneCommand: |
    # If pvm exists, run pvm 8.2
    php configure.php
