name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  node-tests:
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20, 22, 24]
    name: "Build and Test: Node ${{ matrix.node }}"
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-${{ matrix.node }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node }}-turbo-

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Lint
        run: npm run lint

  php-tests:
    name: "PHP Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Run PHP Tests
        uses: alleyinteractive/action-test-php@develop
        with:
          php-version: '8.3'
          skip-audit: 'true'
          skip-core-test-suite: 'true'
          skip-wordpress-install: 'true'
          working-directory: 'plugin'

  all-pr-checks-passed:
    name: All PR checks passed
    needs:
      - node-tests
      - php-tests
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check job statuses
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" ]]; then
            echo "One or more jobs failed"
            exit 1
          elif [[ "${{ contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            echo "One or more jobs were cancelled"
            exit 1
          else
            echo "All jobs passed or were skipped"
            exit 0
          fi
