name: Build and Publish storybook to GitHub Pages

on:
  push:
    branches:
      - main
      - storybook-7

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - id: build-publish
      uses: bitovi/github-actions-react-to-ghp@v1.2.1
      with:
        path: storybook-static
        build_command: npm run build-storybook
