name: "Lerna Package Tests"

on:
  pull_request:

jobs:
  npm-ci:
    name: Audit, Lint, Test, and Build
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs of this workflow (pull requests only)
        if: ${{ github.event_name == 'pull_request' }}
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm ci

      - name: Install Packages
        run: npx lerna bootstrap

      # - name: Audit node
      #   run: npm audit --audit-level=high --production

      - name: Run test
        run: npx lerna run test

      - name: Run lint
        run: npx lerna run lint

      - name: Run build
        run: npx lerna run build
