name: Coding Standards

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  coding-standards:
    if: github.event.pull_request.draft == false
    name: PHP Coding Standards
    uses: alleyinteractive/.github/.github/workflows/php-coding-standards.yml@main
    with:
      working-directory: plugin
