name: Coding Standards

on:
  push:
    branches:
      - develop
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  coding-standards:
    uses: alleyinteractive/.github/.github/workflows/php-coding-standards.yml@working-directory
    with:
      working-directory: plugin
