name: "Package: Block Editor Tools"

on:
  pull_request:

jobs:
  npm-ci:
    name: Install, build, and test
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs of this workflow (pull requests only)
        if: ${{ github.event_name == 'pull_request' }}
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: 16

      - name: Audit node
        working-directory: packages/block-editor-tools
        run: npm audit --audit-level=high --production

      - name: Install node dependencies (npm ci)
        working-directory: packages/block-editor-tools
        run: npm ci --legacy-peer-deps

      - name: Run npm test
        working-directory: packages/block-editor-tools
        run: npm run test

      - name: Run npm lint
        working-directory: packages/block-editor-tools
        run: npm run lint

      - name: Run npm build
        working-directory: packages/block-editor-tools
        run: npm run build
